"""Traces the product photos into SVG paths for the overlay.

Run from the repo root:
    uv run --with opencv-python-headless --with numpy ref/trace.py

Reads ref/img0.jpg (front) and ref/img6.jpg (left side), writes web/traced.js with
paths in each photo's own pixel coordinates, plus ref/trace_*.png previews to check
the traces against the photos. Live parts (antenna split, sticks, paddles) are cut out
so the page can draw them itself.
"""
import json
from pathlib import Path

import cv2
import numpy as np

HERE = Path(__file__).parent
WEB = HERE.parent / "web"

# Front photo: rows above the shell's top edge hold the antenna and the SB/SC nubs.
FRONT_TOP_EDGE = 346
FRONT_NUBS = [(340, 300, 392, FRONT_TOP_EDGE), (608, 300, 664, FRONT_TOP_EDGE)]
# Side photo: the left gimbal stick pokes out of the face here.
SIDE_STICK = (616, 470, 700, 520)
# The grip only covers the rear-lower part of the side.
SIDE_GRIP_TOP = 370
SIDE_GRIP_RIGHT = 520


def silhouette(img):
    """Radio vs. white studio background, holes filled."""
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    mask = ((gray < 238) | (hsv[..., 1] > 30)).astype(np.uint8) * 255
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((7, 7), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8))
    ff = mask.copy()
    h, w = mask.shape
    cv2.floodFill(ff, np.zeros((h + 2, w + 2), np.uint8), (0, 0), 255)
    return mask | cv2.bitwise_not(ff)


def largest_path(mask, eps=1.0):
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    c = max(contours, key=cv2.contourArea)
    approx = cv2.approxPolyDP(c, eps, True)
    pts = approx.reshape(-1, 2)
    d = "M" + "L".join(f"{x} {y}" for x, y in pts) + "Z"
    return d, approx


def clear(mask, box):
    x0, y0, x1, y1 = box
    mask[y0:y1, x0:x1] = 0


def cut_along_face(mask, box):
    """Removes whatever sticks out of the face inside `box` by cutting along the straight
    line joining the face edge just above and just below it (the face slants here, so a
    rectangular cut would leave a step)."""
    x0, y0, x1, y1 = box

    def edge(y):
        cols = np.flatnonzero(mask[y, :x1])
        return cols.max() if cols.size else x0

    top, bottom = edge(y0 - 2), edge(y1 + 2)
    for y in range(y0 - 2, y1 + 3):
        t = (y - (y0 - 2)) / ((y1 + 2) - (y0 - 2))
        face = round(top + (bottom - top) * t)
        mask[y, face + 1 : x1] = 0


def main():
    out = {}
    previews = {}

    front = cv2.imread(str(HERE / "img0.jpg"))
    m = silhouette(front)
    body = m.copy()
    body[:FRONT_TOP_EDGE] = 0
    antenna = m.copy()
    antenna[FRONT_TOP_EDGE:] = 0
    for box in FRONT_NUBS:
        clear(antenna, box)
    out["frontBody"], a1 = largest_path(body)
    out["frontAntenna"], a2 = largest_path(antenna)
    previews["front"] = (front, [a1, a2])

    side = cv2.imread(str(HERE / "img6.jpg"))
    m = silhouette(side)
    cut_along_face(m, SIDE_STICK)
    out["sideBody"], a3 = largest_path(m)
    # Rubber grip: neutral grey (low saturation), unlike the brown-tinted smoky shell.
    sat = cv2.cvtColor(side, cv2.COLOR_BGR2HSV)[..., 1]
    grip = ((sat < 26) & (m > 0)).astype(np.uint8) * 255
    grip[:SIDE_GRIP_TOP] = 0
    grip[:, SIDE_GRIP_RIGHT:] = 0
    grip = cv2.morphologyEx(grip, cv2.MORPH_OPEN, np.ones((9, 9), np.uint8))
    grip = cv2.morphologyEx(grip, cv2.MORPH_CLOSE, np.ones((25, 25), np.uint8))
    # Smooth the blocky edges the morphology leaves behind.
    grip = (cv2.GaussianBlur(grip, (31, 31), 0) > 140).astype(np.uint8) * 255
    out["sideGrip"], a4 = largest_path(grip, 1.5)
    previews["side"] = (side, [a3, a4])

    for name, (img, contours) in previews.items():
        p = img.copy()
        cv2.drawContours(p, contours, -1, (0, 0, 255), 2)
        cv2.imwrite(str(HERE / f"trace_{name}.png"), p)

    js = "// generated by ref/trace.py from the RadioMaster product photos - do not edit\n"
    js += f"window.TRACED = {json.dumps(out, indent=1)};\n"
    (WEB / "traced.js").write_text(js)
    print({k: v.count("L") + 1 for k, v in out.items()})


if __name__ == "__main__":
    main()
