//! Shared tooling for the integration tests.
//!
//! - `edgetx_src` / `Encoder`: EdgeTX's own report encoder compiled into a small harness
//!   (falls back to the Rust mirror when the source or a C++ compiler is missing).
//! - `Radio` / `Wiring`: a model of the physical radio. Tests set stick and switch
//!   positions; the wiring (the model's mixes) turns them into channel values.
//! - `Overlay`: the real binary, started with `--replay -` so the test feeds it report
//!   bytes on stdin like a virtual USB device.
//! - `Ws`: WebSocket client that reads the overlay's published state.

#![allow(dead_code)]

use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};
use std::sync::{Arc, Mutex, OnceLock, mpsc};
use std::time::Duration;

use pocket_overlay::config::Source;
use pocket_overlay::edgetx;
use pocket_overlay::learn::Target;

// ---------------------------------------------------------------------------------------
// EdgeTX source + encoder harness

pub fn edgetx_src() -> Option<PathBuf> {
    let dir = std::env::var_os("EDGETX_SRC")
        .map(PathBuf::from)
        .unwrap_or_else(|| Path::new(env!("CARGO_MANIFEST_DIR")).join("ref/edgetx"));
    let src = dir.join("radio/src");
    if src.join("targets/common/arm/stm32/usb_driver.cpp").exists() {
        Some(src)
    } else {
        eprintln!(
            "SKIPPED EdgeTX checks: no source at {} (see tests/edgetx_conformance.rs)",
            dir.display()
        );
        None
    }
}

pub fn read(src: &Path, rel: &str) -> String {
    std::fs::read_to_string(src.join(rel))
        .unwrap_or_else(|e| panic!("reading {rel}: {e}"))
        .replace("\r\n", "\n")
}

/// Text between `start` and the next `end` after it.
pub fn between<'a>(text: &'a str, start: &str, end: &str) -> &'a str {
    let from = text
        .find(start)
        .unwrap_or_else(|| panic!("{start:?} not found"))
        + start.len();
    let len = text[from..]
        .find(end)
        .unwrap_or_else(|| panic!("{end:?} not found after {start:?}"));
    &text[from..from + len]
}

pub fn find_cxx() -> Option<String> {
    let candidates = std::env::var("CXX")
        .into_iter()
        .chain(["clang++".into(), "g++".into()]);
    for cxx in candidates {
        if Command::new(&cxx)
            .arg("--version")
            .output()
            .is_ok_and(|o| o.status.success())
        {
            return Some(cxx);
        }
    }
    eprintln!("SKIPPED EdgeTX encoder: no C++ compiler (set CXX, or install clang++/g++)");
    None
}

/// `HID_JOYSTICK_ReportDesc` bytes straight from the EdgeTX source.
pub fn source_descriptor(src: &Path) -> Vec<u8> {
    let file = read(src, "targets/common/arm/stm32/usbd_hid_joystick.c");
    let body = between(&file, "HID_JOYSTICK_ReportDesc[] __ALIGN_END =", "};");
    body.lines()
        .map(|l| l.split("//").next().unwrap())
        .flat_map(|l| l.split(','))
        .map(str::trim)
        .filter_map(|t| t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")))
        .map(|h| u8::from_str_radix(h, 16).expect("hex byte"))
        .collect()
}

/// A harness around the verbatim classic branch of EdgeTX's `usbJoystickUpdate()`.
/// Reads 32 channel values per line on stdin, prints each report as hex.
pub fn harness_source(src: &Path) -> String {
    let driver = read(src, "targets/common/arm/stm32/usb_driver.cpp");
    let func = between(&driver, "void usbJoystickUpdate()\n{", "\n}\n");
    let classic = between(func, "#if !defined(USBJ_EX)", "#else");

    let conf = read(src, "targets/common/arm/stm32/usbd_conf.h");
    let packet = between(&conf, "#define HID_IN_PACKET", "\n")
        .trim()
        .to_owned();

    let helpers = read(src, "edgetx_helpers.h");
    let limit_at = helpers
        .find("inline T limit(")
        .expect("limit() in edgetx_helpers.h");
    let template_at = helpers[..limit_at]
        .rfind("template")
        .expect("limit template");
    let limit_end = limit_at + helpers[limit_at..].find('}').expect("limit body") + 1;
    let limit = &helpers[template_at..limit_end];

    format!(
        r#"// generated by tests/common/mod.rs from EdgeTX source
#include <cstdint>
#include <cstdio>
#include <algorithm>
using std::min;
using std::max;

#define HID_IN_PACKET {packet}
{limit}

int16_t channelOutputs[32];
static int hUsbDevice;
static void USBD_HID_SendReport(int*, uint8_t* buf, int len) {{
  for (int i = 0; i < len; i++) printf("%02x", buf[i]);
  printf("\n");
  fflush(stdout);
}}

void usbJoystickUpdate() {{
{classic}
}}

int main() {{
  for (;;) {{
    for (int i = 0; i < 32; i++) {{
      int v;
      if (scanf("%d", &v) != 1) return 0;
      channelOutputs[i] = (int16_t)v;
    }}
    usbJoystickUpdate();
  }}
}}
"#
    )
}

/// Builds the harness once per test binary, reusing an existing build when the
/// generated source hasn't changed.
pub fn harness_exe() -> Option<PathBuf> {
    static EXE: OnceLock<Option<PathBuf>> = OnceLock::new();
    EXE.get_or_init(|| {
        let src = edgetx_src()?;
        let cxx = find_cxx()?;
        let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join("edgetx-harness");
        std::fs::create_dir_all(&dir).unwrap();
        let cpp = dir.join("harness.cpp");
        let exe = dir.join(if cfg!(windows) {
            "harness.exe"
        } else {
            "harness"
        });
        let code = harness_source(&src);
        let fresh = std::fs::read_to_string(&cpp).is_ok_and(|old| old == code) && exe.exists();
        if !fresh {
            std::fs::write(&cpp, &code).unwrap();
            let out = Command::new(&cxx)
                .args(["-std=c++17", "-O1"])
                .arg(&cpp)
                .arg("-o")
                .arg(&exe)
                .output()
                .unwrap();
            assert!(
                out.status.success(),
                "harness build failed:\n{}\n{code}",
                String::from_utf8_lossy(&out.stderr)
            );
        }
        Some(exe)
    })
    .clone()
}

pub fn parse_hex(line: &str) -> Vec<u8> {
    (0..line.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&line[i..i + 2], 16).unwrap())
        .collect()
}

pub fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Turns channel values into report bytes: via EdgeTX's own code when available.
pub enum Encoder {
    Edgetx {
        child: Child,
        stdin: ChildStdin,
        stdout: BufReader<ChildStdout>,
    },
    Rust,
}

impl Encoder {
    pub fn best() -> Self {
        match harness_exe() {
            Some(exe) => {
                let mut child = Command::new(exe)
                    .stdin(Stdio::piped())
                    .stdout(Stdio::piped())
                    .spawn()
                    .unwrap();
                let stdin = child.stdin.take().unwrap();
                let stdout = BufReader::new(child.stdout.take().unwrap());
                Encoder::Edgetx {
                    child,
                    stdin,
                    stdout,
                }
            }
            None => Encoder::Rust,
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            Encoder::Edgetx { .. } => "EdgeTX usbJoystickUpdate()",
            Encoder::Rust => "Rust mirror (EdgeTX harness unavailable)",
        }
    }

    pub fn encode(&mut self, ch: &[i16; edgetx::CHANNELS]) -> Vec<u8> {
        match self {
            Encoder::Edgetx { stdin, stdout, .. } => {
                let line: Vec<String> = ch.iter().map(i16::to_string).collect();
                writeln!(stdin, "{}", line.join(" ")).unwrap();
                stdin.flush().unwrap();
                let mut out = String::new();
                stdout.read_line(&mut out).unwrap();
                parse_hex(out.trim())
            }
            Encoder::Rust => edgetx::encode_classic(ch).to_vec(),
        }
    }
}

impl Drop for Encoder {
    fn drop(&mut self) {
        if let Encoder::Edgetx { child, .. } = self {
            let _ = child.kill();
        }
    }
}

// ---------------------------------------------------------------------------------------
// physical radio model

/// Where every physical control is. Sticks and S1 are -1..=1 (up/right = +);
/// switch positions count from "away from the pilot" (0).
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct Radio {
    pub left_x: f32,
    pub left_y: f32,
    pub right_x: f32,
    pub right_y: f32,
    pub sa: u8,
    pub sb: u8,
    pub sc: u8,
    pub sd: u8,
    pub se: bool,
    pub s1: f32,
}

impl Radio {
    /// What EdgeTX's mixer outputs for a control at full weight: -100/+100 for 2-pos,
    /// -100/0/+100 for 3-pos, value*100 for analog.
    pub fn mixer_value(&self, target: Target) -> f32 {
        let two = |p: u8| if p == 0 { -1.0 } else { 1.0 };
        match target {
            Target::LeftX => self.left_x,
            Target::LeftY => self.left_y,
            Target::RightX => self.right_x,
            Target::RightY => self.right_y,
            Target::SA => two(self.sa),
            Target::SD => two(self.sd),
            Target::SB => self.sb as f32 - 1.0,
            Target::SC => self.sc as f32 - 1.0,
            Target::SE => two(self.se as u8),
            Target::S1 => self.s1,
        }
    }
}

/// The model's mixes: which channel each control drives, and whether it's reversed.
#[derive(Debug, Clone, PartialEq)]
pub struct Wiring(pub Vec<(Target, Source)>);

impl Wiring {
    /// Same as the overlay's default config.
    pub fn default_pocket() -> Self {
        let s = |ch| Source { ch, invert: false };
        Wiring(vec![
            (Target::RightX, s(1)),
            (Target::RightY, s(2)),
            (Target::LeftY, s(3)),
            (Target::LeftX, s(4)),
            (Target::SA, s(5)),
            (Target::SB, s(6)),
            (Target::SC, s(7)),
            (Target::S1, s(8)),
            (Target::SD, s(9)),
            (Target::SE, s(10)),
        ])
    }

    /// Random channels (analog controls on CH1-8, the rest anywhere) and random reversing.
    pub fn random(rng: &mut Rng) -> Self {
        let mut analog: Vec<usize> = (1..=8).collect();
        let mut any: Vec<usize> = Vec::new();
        rng.shuffle(&mut analog);
        let mut wiring = Vec::new();
        for t in pocket_overlay::learn::Target::ALL {
            if t.needs_analog() {
                let ch = analog.pop().unwrap();
                wiring.push((
                    t,
                    Source {
                        ch,
                        invert: rng.below(2) == 1,
                    },
                ));
            }
        }
        // 2-pos switches and SE: leftover analog channels or button channels 9-32
        any.extend(analog);
        any.extend(9..=32);
        rng.shuffle(&mut any);
        for t in [Target::SA, Target::SD, Target::SE] {
            wiring.push((
                t,
                Source {
                    ch: any.pop().unwrap(),
                    invert: rng.below(2) == 1,
                },
            ));
        }
        Wiring(wiring)
    }

    pub fn get(&self, t: Target) -> Option<Source> {
        self.0
            .iter()
            .find(|(target, _)| *target == t)
            .map(|(_, s)| *s)
    }

    pub fn channels(&self, radio: &Radio) -> [i16; edgetx::CHANNELS] {
        let mut ch = [0i16; edgetx::CHANNELS];
        for (target, src) in &self.0 {
            let v = radio.mixer_value(*target) * if src.invert { -1.0 } else { 1.0 };
            ch[src.ch - 1] = (v * 1024.0).round() as i16;
        }
        ch
    }
}

/// Small deterministic PRNG (xorshift) so failures reproduce.
pub struct Rng(pub u64);

impl Rng {
    pub fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }
    pub fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
    /// Uniform in -1..=1 on a 1/1024 grid, so it survives the trip exactly.
    pub fn unit(&mut self) -> f32 {
        (self.below(2049) as f32 - 1024.0) / 1024.0
    }
    pub fn shuffle<T>(&mut self, v: &mut [T]) {
        for i in (1..v.len()).rev() {
            v.swap(i, self.below(i as u64 + 1) as usize);
        }
    }
    pub fn radio(&mut self) -> Radio {
        Radio {
            left_x: self.unit(),
            left_y: self.unit(),
            right_x: self.unit(),
            right_y: self.unit(),
            sa: self.below(2) as u8,
            sb: self.below(3) as u8,
            sc: self.below(3) as u8,
            sd: self.below(2) as u8,
            se: self.below(2) == 1,
            s1: self.unit(),
        }
    }
}

// ---------------------------------------------------------------------------------------
// the overlay process

pub struct Overlay {
    child: Child,
    stdin: ChildStdin,
    pub port: u16,
    pub dir: tempfile::TempDir,
    pub log: Arc<Mutex<Vec<String>>>,
    encoder: Encoder,
    pub wiring: Wiring,
    /// Hex of the last report sent, for recording evidence.
    pub last_report: String,
}

impl Overlay {
    pub fn start() -> Self {
        Self::start_with(None)
    }

    /// Starts the binary reading reports from stdin. `config` is written as overlay.toml
    /// first; otherwise the binary writes its defaults.
    pub fn start_with(config: Option<&str>) -> Self {
        Self::launch(&["--replay", "-"], config)
    }

    /// Starts the binary with other input arguments (`--demo`, `--replay <file>`).
    pub fn launch(input: &[&str], config: Option<&str>) -> Self {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("overlay.toml");
        if let Some(text) = config {
            std::fs::write(&cfg, text).unwrap();
        }
        let mut child = Command::new(env!("CARGO_BIN_EXE_pocket-overlay"))
            .args(input)
            .args(["--port", "0", "--config"])
            .arg(&cfg)
            .current_dir(dir.path()) // no web/ override: test the embedded page
            .stdin(Stdio::piped())
            .stderr(Stdio::piped())
            .stdout(Stdio::null())
            .spawn()
            .unwrap();
        let stdin = child.stdin.take().unwrap();
        let log = Arc::new(Mutex::new(Vec::new()));
        let (port_tx, port_rx) = mpsc::channel();
        let stderr = child.stderr.take().unwrap();
        let log2 = log.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(stderr).lines().map_while(Result::ok) {
                // first URL the app prints is the overlay's
                if let Some(rest) = line.split("http://127.0.0.1:").nth(1)
                    && let Ok(port) = rest.split('/').next().unwrap().parse::<u16>()
                {
                    let _ = port_tx.send(port);
                }
                log2.lock().unwrap().push(line);
            }
        });
        let port = port_rx
            .recv_timeout(Duration::from_secs(10))
            .unwrap_or_else(|_| panic!("overlay didn't start: {:?}", log.lock().unwrap()));
        Overlay {
            child,
            stdin,
            port,
            dir,
            log,
            encoder: Encoder::best(),
            wiring: Wiring::default_pocket(),
            last_report: String::new(),
        }
    }

    pub fn encoder_name(&self) -> &'static str {
        self.encoder.name()
    }

    pub fn line(&mut self, s: &str) {
        writeln!(self.stdin, "{s}").unwrap();
        self.stdin.flush().unwrap();
    }

    /// Sends channels straight through the Rust encoder (fast, for floods).
    pub fn channels_fast(&mut self, ch: &[i16; edgetx::CHANNELS]) {
        self.line(&to_hex(&edgetx::encode_classic(ch)));
    }

    pub fn channels(&mut self, ch: &[i16; edgetx::CHANNELS]) {
        let bytes = self.encoder.encode(ch);
        self.last_report = to_hex(&bytes);
        let line = self.last_report.clone();
        self.line(&line);
    }

    /// Puts the physical radio in `radio`'s position (through the current wiring).
    pub fn radio(&mut self, radio: &Radio) {
        let ch = self.wiring.channels(radio);
        self.channels(&ch);
    }

    pub fn url(&self, query: &str) -> String {
        format!("http://127.0.0.1:{}/{query}", self.port)
    }

    pub fn config_text(&self) -> String {
        std::fs::read_to_string(self.dir.path().join("overlay.toml")).unwrap()
    }
}

impl Drop for Overlay {
    fn drop(&mut self) {
        let _ = self.child.kill();
    }
}

/// Channel values joined with commas, as the page's `data-channels` shows them.
pub fn channel_key(ch: &[i16]) -> String {
    ch.iter().map(i16::to_string).collect::<Vec<_>>().join(",")
}

/// What the decoded channels should be: axes clamp to +-1024, buttons read +-1024.
pub fn expected_channels(ch: &[i16; edgetx::CHANNELS]) -> [i16; edgetx::CHANNELS] {
    let mut out = [0i16; edgetx::CHANNELS];
    for (i, v) in ch.iter().enumerate() {
        out[i] = if i < edgetx::AXES {
            (*v).clamp(-1024, 1024)
        } else if *v > 0 {
            1024
        } else {
            -1024
        };
    }
    out
}

// ---------------------------------------------------------------------------------------
// WebSocket client

pub mod ws {
    use std::time::Duration;

    use futures_util::{SinkExt, StreamExt};
    use serde_json::Value;
    use tokio_tungstenite::tungstenite::Message;

    pub struct Ws {
        stream: tokio_tungstenite::WebSocketStream<
            tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>,
        >,
        pub last: Value,
    }

    impl Ws {
        pub async fn connect(port: u16) -> Self {
            let (stream, _) = tokio_tungstenite::connect_async(format!("ws://127.0.0.1:{port}/ws"))
                .await
                .unwrap();
            let mut ws = Ws {
                stream,
                last: Value::Null,
            };
            ws.next().await;
            ws
        }

        async fn next(&mut self) -> &Value {
            loop {
                match self.stream.next().await {
                    Some(Ok(Message::Text(t))) => {
                        self.last = serde_json::from_str(&t).unwrap();
                        return &self.last;
                    }
                    Some(Ok(_)) => {}
                    other => panic!("websocket ended: {other:?}"),
                }
            }
        }

        /// Waits for a published state that satisfies `pred`.
        pub async fn wait_for(&mut self, what: &str, pred: impl Fn(&Value) -> bool) -> Value {
            if pred(&self.last) {
                return self.last.clone();
            }
            let deadline = tokio::time::Instant::now() + Duration::from_secs(8);
            loop {
                match tokio::time::timeout_at(deadline, self.next()).await {
                    Ok(v) if pred(v) => return v.clone(),
                    Ok(_) => {}
                    Err(_) => panic!("timed out waiting for {what}; last state:\n{:#}", self.last),
                }
            }
        }

        /// Waits for the next message, whatever it says.
        pub async fn recv(&mut self) -> Value {
            self.next().await.clone()
        }

        pub async fn command(&mut self, cmd: &str) {
            self.send_json(serde_json::json!({ "cmd": cmd })).await;
        }

        pub async fn send_json(&mut self, msg: Value) {
            self.stream
                .send(Message::Text(msg.to_string().into()))
                .await
                .unwrap();
        }
    }
}

// ---------------------------------------------------------------------------------------
// plain HTTP and a test skin

/// A 1 x 1 opaque red PNG.
pub const RED_PNG: [u8; 70] = [
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4,
    0x89, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0xf8, 0xcf, 0xc0, 0xf0,
    0x1f, 0x00, 0x05, 0x00, 0x01, 0xff, 0x89, 0x99, 0x3d, 0x1d, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45,
    0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
];

/// Minimal HTTP/1.1 request; returns (status, headers, body). `host` overrides the Host
/// header (for the "other website" tests).
pub fn http(
    port: u16,
    method: &str,
    path: &str,
    extra_headers: &[(&str, &str)],
    body: &[u8],
) -> (u16, String, Vec<u8>) {
    use std::io::Read;
    let mut s = std::net::TcpStream::connect(("127.0.0.1", port)).unwrap();
    let mut req = format!(
        "{method} {path} HTTP/1.1\r\nConnection: close\r\nContent-Length: {}\r\n",
        body.len()
    );
    if !extra_headers
        .iter()
        .any(|(k, _)| k.eq_ignore_ascii_case("host"))
    {
        req.push_str(&format!("Host: 127.0.0.1:{port}\r\n"));
    }
    for (k, v) in extra_headers {
        req.push_str(&format!("{k}: {v}\r\n"));
    }
    req.push_str("\r\n");
    s.write_all(req.as_bytes()).unwrap();
    s.write_all(body).unwrap();
    let mut raw = Vec::new();
    s.read_to_end(&mut raw).unwrap();
    let split = raw
        .windows(4)
        .position(|w| w == b"\r\n\r\n")
        .expect("response head");
    let head = String::from_utf8_lossy(&raw[..split]).into_owned();
    let status: u16 = head.split_whitespace().nth(1).unwrap().parse().unwrap();
    let mut body = raw[split + 4..].to_vec();
    if head
        .to_ascii_lowercase()
        .contains("transfer-encoding: chunked")
    {
        body = dechunk(&body);
    }
    (status, head, body)
}

fn dechunk(mut data: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    loop {
        let line_end = data.windows(2).position(|w| w == b"\r\n").unwrap();
        let size =
            usize::from_str_radix(std::str::from_utf8(&data[..line_end]).unwrap().trim(), 16)
                .unwrap();
        data = &data[line_end + 2..];
        if size == 0 {
            return out;
        }
        out.extend_from_slice(&data[..size]);
        data = &data[size + 2..];
    }
}
