"""Mutation check for the black-box tests: plant one realistic bug at a time and make
sure the tests notice. Every file is restored afterwards, even on Ctrl+C.

    python tools/mutants.py            # all mutants
    python tools/mutants.py arc paddle # only mutants whose name contains one of these
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (name, file, original, mutated, test binary, test filter)
MUTANTS = [
    ("stick y drawn inverted", "web/index.html",
     "y = g.cy - sy * TRAVEL_Y; // up", "y = g.cy + sy * TRAVEL_Y; // up", "blackbox_render", "sticks"),
    ("stick x drawn inverted", "web/index.html",
     "const x = g.cx + sx * TRAVEL_X, y", "const x = g.cx - sx * TRAVEL_X, y", "blackbox_render", "sticks"),
    ("gimbal drum doesn't tilt with the stick", "web/index.html",
     "const phi = Math.asin(sy * SWING);", "const phi = 0;", "blackbox_render", "sticks"),
    ("gimbal drum tilts the wrong way", "web/index.html",
     "const phi = Math.asin(sy * SWING);", "const phi = Math.asin(-sy * SWING);", "blackbox_render", "sticks"),
    ("gimbal slot slides instead of tilting (no foreshortening)", "web/index.html",
     "return [cy - DRUM_R * Math.sin(phi + d), cy - DRUM_R * Math.sin(phi - d)];",
     "return [cy - DRUM_R * Math.sin(phi) - half, cy - DRUM_R * Math.sin(phi) + half];",
     "blackbox_render", "sticks"),
    ("paddle leans the wrong way", "web/index.html",
     "rotate(${pos ? 14 : -14}", "rotate(${pos ? -14 : 14}", "blackbox_render", "switches"),
    ("nub heights reversed", "web/index.html",
     "NUB_H = [13, 20, 27]", "NUB_H = [27, 20, 13]", "blackbox_render", "switches"),
    ("channel bar on the wrong side", "web/index.html",
     "e.bar.setAttribute(\"x\", e.x + half + Math.min(0, len))", "e.bar.setAttribute(\"x\", e.x + half - Math.min(0, len))",
     "blackbox_render", "pot_channel"),
    ("button lit at zero", "web/index.html",
     "(s.channels[i + 8] ?? 0) > 0", "(s.channels[i + 8] ?? 0) >= 0", "blackbox_render", "disconnect_dims"),
    ("mode 1 throttle on the wrong stick", "web/index.html",
     "1: { THR: [\"right\", \"y\"]", "1: { THR: [\"left\", \"y\"]", "blackbox_render", "readout_follows"),
    ("left stick axes swapped", "src/overlay.rs",
     "left: stick(s.left_x, s.left_y)", "left: stick(s.left_y, s.left_x)", "blackbox_ws", "physical_controls"),
    ("3-pos switch ends swapped", "src/overlay.rs",
     "3 if v < -SWITCH_MIDDLE => 0,", "3 if v < -SWITCH_MIDDLE => 2,", "blackbox_ws", "physical_controls"),
    ("3-pos middle band too wide for low mix weights", "src/overlay.rs",
     "const SWITCH_MIDDLE: f32 = 0.1;", "const SWITCH_MIDDLE: f32 = 0.33;", "blackbox_ws", "low_mix_weights"),
    ("a small deadzone on the sticks", "src/overlay.rs",
     "let v = f32::from(r.channel(src.ch).unwrap_or(0)) / 1024.0;",
     "let v = f32::from(r.channel(src.ch).unwrap_or(0)) / 1024.0;\n    let v = if v.abs() < 0.03 { 0.0 } else { v };",
     "blackbox_ws", "not_deadzoned"),
    ("updates not capped per frame", "src/server.rs",
     "tokio::time::sleep_until(sent_at + MIN_FRAME).await;", "let _ = sent_at;",
     "blackbox_ws", "radio_rate_flood"),
    ("unplugging leaves the last position on screen", "src/input.rs",
     "tx.send_replace(RawState::default());\n                    // look again soon",
     "// look again soon", "hid_backend", "unplug_and_replug"),
    ("a quiet radio treated as unplugged", "src/input.rs",
     "Ok(0) => continue,", "Ok(0) => return true,", "hid_backend", "quiet_radio"),
    ("gives up when another program has the radio", "src/input.rs",
     'eprintln!("Found {name} but couldn\'t open it ({e}); retrying.");', "return;",
     "hid_backend", "locked"),
    ("wrong radio picked when two are plugged in", "src/input.rs",
     '.find(|(_, name)| name.contains("Pocket"))', '.find(|(_, name)| name.contains("no such radio"))',
     "hid_backend", "prefers_the_pocket"),
    ("skin wrap not cropped to the radio's outline", "web/index.html",
     '<g id="skinWrap" clip-path="url(#bodyClip)">', '<g id="skinWrap">',
     "blackbox_render", "a_skin_wraps"),
    ("a missing skin blanks the radio", "web/index.html",
     "probe.onerror = () => { if (shownSkin === key) show(null); };",
     "probe.onerror = () => { if (shownSkin === key) show(href, name); };",
     "blackbox_render", "the_saved_skin"),
    ("skin names not checked (path traversal)", "src/skins.rs",
     "        if valid_name(name) {\n            Ok(self.dir.join", "        if true {\n            Ok(self.dir.join",
     "skins", "bad_skins"),
    ("other websites let in", "src/server.rs",
     "    host_ok && origin_ok\n", "    let _ = (host_ok, origin_ok);\n    true\n",
     "skins", "other_websites"),
    ("axis scaling off by one", "src/hid.rs",
     "(scaled - 1024) as i16", "(scaled - 1023) as i16", "blackbox_ws", "every_channel"),
    ("button bits shifted", "src/hid.rs",
     "if byte >> (bit % 8) & 1 == 1", "if byte >> ((bit + 1) % 8) & 1 == 1", "blackbox_ws", "every_channel"),
    ("wizard records direction backwards", "src/learn.rs",
     "invert: v < 0", "invert: v > 0", "blackbox_ws", "wizard_learns_random_wiring_1"),
    ("wizard refuses on/off channels for sticks and S1", "src/learn.rs",
     "if best.is_none_or(|(_, range)| range < MIN_RANGE) {", "if false {", "blackbox_ws", "wizard_takes_on_off"),
    ("wizard doesn't prefer CH1-8 when a control is on both kinds", "src/learn.rs",
     "self.busiest(|ch| ch <= axes)", "self.busiest(|_| true)", "blackbox_ws", "mixed_to_several"),
    ("a stick on two channels counts as two sticks moving", "src/learn.rs",
     "&& !self.twins(ch, b)", "", "blackbox_ws", "mixed_to_several"),
    ("wizard doesn't look for a channel per position", "src/learn.rs",
     ".flatten().count() >= 2", ".flatten().count() >= 4", "blackbox_ws", "channel_per_position"),
    ("wizard waits forever for a middle that looks like an end", "src/learn.rs",
     "let unseen_middle = n == 3", "let unseen_middle = false && n == 3", "blackbox_ws", "wizard_takes_on_off"),
    ("wizard reverses a switch on one on/off channel", "src/learn.rs",
     "let invert = at(toward, ch) < at(0, ch);", "let invert = at(toward, ch) > at(0, ch);",
     "blackbox_ws", "wizard_takes_on_off"),
    ("a 3-pos switch on one on/off channel draws its middle at an end", "src/overlay.rs",
     "Mapping::Channel(src) if r.is_button(src.ch) => on_off_pos(r, src),", "",
     "blackbox_ws", "wizard_takes_on_off"),
    ("a channel per position read upside down", "src/overlay.rs",
     "let chans = p.channels();", "let mut chans = p.channels();\n    chans.reverse();",
     "blackbox_ws", "channel_per_position"),
    ("open to other PCs before it's switched on", "src/network.rs",
     "return TcpListener::bind((Ipv4Addr::LOCALHOST, port)).await;",
     "return TcpListener::bind((Ipv4Addr::UNSPECIFIED, port)).await;", "network", "only_while"),
    ("switching it on doesn't open the port", "src/server.rs",
     "match network::listen(self.port, shared).await {", "match network::listen(self.port, false).await {",
     "network", "only_while"),
    ("pages on other PCs stay connected after it's switched off", "src/server.rs",
     "if watch_only && !app.state.borrow().lan {", "if false {", "network", "only_while"),
    ("other PCs can change settings", "src/server.rs",
     "Ok(_) if watch_only => {}", "", "network", "only_watch"),
    ("other PCs can upload and delete skins", "src/server.rs",
     "if !conn.this_pc() && !matches!(", "if false && !matches!(", "network", "only_watch"),
    ("any name gets in while shared (DNS rebinding)", "src/server.rs",
     "(lan && names.contains(&host))", "lan", "network", "name_and_nothing_else"),
    ("the labels switch does nothing", "web/index.html",
     '$("tags").style.display = labels ? "" : "none";', '$("tags").style.display = "";',
     "blackbox_render", "switch_labels"),
    ("?labels= ignored", "web/index.html",
     "applyLabels(showPart(LABELS_PARAM, parts.labels));", "applyLabels(parts.labels);",
     "blackbox_render", "switch_labels"),
    ("the antenna switch does nothing", "web/index.html",
     '$("antenna").style.display = antenna ? "" : "none";', '$("antenna").style.display = "";',
     "blackbox_render", "antenna"),
    ("?antenna= ignored", "web/index.html",
     "applyAntenna(showPart(ANTENNA_PARAM, parts.antenna));", "applyAntenna(parts.antenna);",
     "blackbox_render", "antenna"),
    ("the antenna isn't saved", "src/engine.rs",
     "c.show_antenna = antenna;", "",
     "blackbox_ws", "antenna"),
    ("the paddles light up where they always did (the pick ignored)", "web/index.html",
     'shape.classList.toggle("lit", lights(key, v));', 'shape.classList.toggle("lit", v === 1);',
     "blackbox_render", "lights_up"),
    ("S1 has no middle to light up in", "web/index.html",
     "v < -0.02 ? 0 : v > 0.02 ? 2 : 1;", "v < 0 ? 0 : 2;",
     "blackbox_render", "lights_up"),
    ("the Lights up table redrawn every frame (clicks get lost)", "web/index.html",
     "if (built !== mapBuilt) {", "if (true) {",
     "blackbox_render", "lights_up"),
    ("where a switch lights up isn't kept", "src/engine.rs",
     "if changed && self.config.set_lit(&control, &at) {", "if false && self.config.set_lit(&control, &at) {",
     "blackbox_ws", "lights_up"),
    ("S1's deadzone ignored (always ±2%)", "web/index.html",
     "v < -dz / 100 ? 0 : v > dz / 100 ? 2 : 1;", "v < -0.02 ? 0 : v > 0.02 ? 2 : 1;",
     "blackbox_render", "deadzone"),
    ("dragging S1's deadzone does nothing", "web/index.html",
     "return Math.abs((e.clientX - b.left) / b.width * 200 - 100); };", "return 22; };",
     "blackbox_render", "deadzone"),
    ("typing S1's deadzone does nothing", "web/index.html",
     "if (Number.isInteger(v) && v >= 0 && v <= 50) chooseDeadzone(v, true);", "",
     "blackbox_render", "deadzone"),
    ("S1's deadzone isn't kept", "src/engine.rs",
     "if percent <= MAX_S1_DEADZONE && percent != self.config.s1_deadzone {",
     "if false && percent != self.config.s1_deadzone {",
     "blackbox_ws", "deadzone"),
    ("the shadow switch does nothing", "web/index.html",
     '$("shadow").style.display = shadow ? "" : "none";', '$("shadow").style.display = "";',
     "blackbox_render", "shadow"),
    ("the shadow's angle ignored", "web/index.html",
     '$("floatOffset").setAttribute("dx", (sh.distance * Math.sin(rad)).toFixed(2));', "",
     "blackbox_render", "shadow"),
    ("the shadow's blur ignored", "web/index.html",
     '$("floatBlur").setAttribute("stdDeviation", sh.blur);', '$("floatBlur").setAttribute("stdDeviation", 6);',
     "blackbox_render", "shadow"),
    ("the shadow's strength ignored", "web/index.html",
     '$("floatAlpha").setAttribute("slope", sh.strength / 100);', '$("floatAlpha").setAttribute("slope", 0.6);',
     "blackbox_render", "shadow"),
    ("the shadow's look isn't kept", "src/engine.rs",
     "if shadow.valid() && shadow != self.config.shadow {", "if false && shadow != self.config.shadow {",
     "blackbox_ws", "shadow"),
    ("opening the shadow's sliders moves the settings sideways (the scrollbar)", "web/index.html",
     "scrollbar-gutter: stable; ", "",
     "blackbox_render", "shadow"),
    ("the LAN note beside the address (the switch moves when it's switched)", "web/index.html",
     ".status .obs, #lanNote { grid-column: 1 / -1; }", ".status .obs, #lanNote { grid-column: auto; }",
     "blackbox_render", "another_pc"),
    ("the other PC's page shows the settings", "web/index.html",
     'const SETUP = q.get("setup") === "1" && !OTHER_PC;', 'const SETUP = q.get("setup") === "1";',
     "blackbox_render", "another_pc"),
    ("the settings page keeps showing 127.0.0.1 when shared", "web/index.html",
     'obsUrl = urlFor(name || ip || "127.0.0.1");', 'obsUrl = urlFor("127.0.0.1");',
     "blackbox_render", "another_pc"),
    ("accent colour not checked (it goes into the page's CSS)", "src/engine.rs",
     "let ok = accent.as_deref().is_none_or(crate::config::valid_colour);", "let ok = true;",
     "blackbox_ws", "accent_colour"),
    ("OBS ignores the saved accent colour", "web/index.html",
     "if (!ACCENT_PARAM) applyAccent(", "if (false) applyAccent(", "blackbox_render", "accent_picked"),
    ("OBS ignores the saved strip choice", "web/index.html",
     'const showPart = (param, saved) => (param === null ? saved : param !== "0");',
     'const showPart = (param, saved) => (param === null ? true : param !== "0");',
     "blackbox_render", "the_strip"),
    ("?channels= and ?readout= ignored", "web/index.html",
     'const showPart = (param, saved) => (param === null ? saved : param !== "0");',
     "const showPart = (param, saved) => saved;", "blackbox_render", "the_strip"),
    ("radio moves when the strip is hidden", "web/index.html",
     ' preserveAspectRatio="xMidYMin meet">', ">", "blackbox_render", "the_strip"),
    ("bars leave a gap where the readout was", "web/index.html",
     'readout ? "" : "translate(0 -38)"', '""', "blackbox_render", "the_strip"),
    ("wizard runs on the demo's made-up input", "src/engine.rs",
     "if !self.raw.connected || self.raw.demo {", "if !self.raw.connected {", "blackbox_ws", "no_channel_detection"),
    ("wizard starts with no radio", "src/engine.rs",
     "if !self.raw.connected || self.raw.demo {", "if self.raw.demo {", "blackbox_ws", "no_channel_detection"),
    ("setup page flags SB on CH9-32 as a mistake", "web/index.html",
     "const odd = !onOff && want", "const odd = want", "blackbox_render", "how_each_control"),
    ("setup page shows a channel per position as nothing", "web/index.html",
     "if (!src.ch) return", "if (false) return", "blackbox_render", "how_each_control"),
    ("setup page lets you start detection when it can't work", "web/index.html",
     '$("bStart").disabled = running || !!why;', '$("bStart").disabled = running;',
     "blackbox_render", "channel_detection_says"),
    ("setup page's radio scrolls away with the settings", "web/index.html",
     "body.setup { background: #0e0f11; display: grid; height: 100vh; }",
     "body.setup { background: #0e0f11; overflow: auto; }", "blackbox_render", "everything_stays"),
    ("a moved port isn't saved (the OBS URL would change every start)", "src/main.rs",
     'cfg.save(&args.config).context("saving the new port")?;', "", "blackbox_ws", "moves_to_a_free_one"),
    ("the OBS page gets a background (a box in the scene)", "web/index.html",
     "html, body { margin: 0; background: transparent;", "html, body { margin: 0; background: #0e0f11;",
     "blackbox_render", "see_through"),
    ("--port ignored", "src/main.rs",
     "let port = args.port.unwrap_or(cfg.port);", "let port = cfg.port;",
     "blackbox_ws", "asked_for_is_used"),
    ("--port saved with the next settings change", "src/main.rs",
     "let engine = Engine::new(cfg.clone(), args.config.clone());",
     "let engine = Engine::new(Config { port, ..cfg.clone() }, args.config.clone());",
     "blackbox_ws", "asked_for_stays_out"),
    ("descriptor ignored", "src/input.rs",
     "state.layout = describe(&l);\n                    layout = l;", "state.layout = describe(&l);",
     "blackbox_ws", "uses_the_layout"),
]


def run(test, filt):
    r = subprocess.run(["cargo", "test", "-q", "--test", test, "--", filt],
                       cwd=ROOT, capture_output=True, text=True)
    return r.returncode == 0


def main():
    wanted = sys.argv[1:]
    results = []
    for name, rel, orig, mutated, test, filt in MUTANTS:
        if wanted and not any(w in name for w in wanted):
            continue
        path = ROOT / rel
        text = path.read_text(encoding="utf8")
        assert text.count(orig) == 1, f"{name}: pattern found {text.count(orig)} times in {rel}"
        try:
            path.write_text(text.replace(orig, mutated), encoding="utf8", newline="\n")
            passed = run(test, filt)
        finally:
            path.write_text(text, encoding="utf8", newline="\n")
        verdict = "SURVIVED (tests missed it)" if passed else "caught"
        print(f"{verdict:28} {name}", flush=True)
        results.append(passed)
    survivors = sum(results)
    print(f"\n{len(results) - survivors}/{len(results)} mutants caught")
    sys.exit(1 if survivors else 0)


if __name__ == "__main__":
    main()
